version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  server:
    build: .  # 서버의 Dockerfile 경로
    ports:
      - "8091:8091"
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGODB_URI: ${MONGODB_URI}
    depends_on:
      - mongo

  client:
    build: ./chat/client/svelte-chat  # 클라이언트의 Dockerfile 경로
    ports:
      - "5001:5001"
    environment:
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - server

volumes:
  mongo-data: